baseURL = 'http://efym.net/'
languageCode = 'en-us'
title = 'efym.net'
theme = 'tugo'

[outputs]
home = [ "RSS", "HTML"]
section  = ["HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
