name: release

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.2'

      - run: hugo --minify

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: tw1zr99/lab
          token: ${{ secrets.GITOPS_PAT }}
          path: lab
          ref: master

      - name: Patch efym.net image tag
        run: |
          IMAGE_TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_URI=ghcr.io/tw1zr99/efym.net:$IMAGE_TAG

          sed -i "s|image:.*|image: $IMAGE_URI|" lab/kubernetes/apps/efym-net/deployment.yaml

      - name: Create or update PR in lab repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITOPS_PAT }}
          commit-message: "Update efym.net image to sha-${{ github.sha }}"
          title: "Update efym.net image to sha-${{ github.sha }}"
          body: |
            Automated update of efym.net image tag to:
            ```
            ghcr.io/tw1zr99/efym.net:sha-${{ github.sha }}
            ```
            Triggered by changes to the efym.net repository.
          base: master
          branch: develop
          path: lab
