name: CI Checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  markdownlint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint via reviewdog
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff

  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile

  # spellcheck:
  #   name: Spellcheck Markdown
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run cspell
  #       uses: streetsidesoftware/cspell-action@v7
  #       with:
  #         args: '"content/**/*.md"'

  # html-validate:
  #   name: Validate Generated HTML
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Hugo
  #       uses: peaceiris/actions-hugo@v3
  #       with:
  #         hugo-version: '0.140.2'
  #     - name: Build Hugo site
  #       run: hugo --minify
  #     - name: HTML5Validator
  #       uses: Cyb3r-Jak3/html5validator-action@v7.2.0
  #       with:
  #         root: public
  #         skip_git_check: true
