name: CI Checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  markdownlint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint via reviewdog
        uses: reviewdog/action-markdownlint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff

  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile

  spellcheck:
    name: Spellcheck Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cspell
        uses: joerick/cspell-action@v4
        with:
          args: '"content/**/*.md"'

  html-validate:
    name: Validate Generated HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.2'
      - name: Build Hugo site
        run: hugo --minify
      - name: Run W3C HTML Validator
        uses: gauntface/html-validator-action@v1
        with:
          files: public/**/*.html

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.2'
      - name: Build Hugo site
        run: hugo --minify
      - name: Serve site locally
        run: |
          npm install -g http-server
          http-server public -p 8080 &
          sleep 5
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: http://localhost:8080
